### ISSUE TITLE
建议增加持续时间

### ISSUE THREAD

**Issue by VwEl** [moonrailgun/BilibiliLiveSend#1]
并且能自定义间隔

**Comment by moonrailgun** [comment]
`v0.0.2` 增加了自定义弹幕的时间间隔
持续时间设置可以通过自定义间隔*连续发送弹幕数来实现
[点击此处下载离线安装插件包](https://github.com/moonrailgun/BilibiliLiveSend/releases/download/0.0.2/BilibiliLiveSend.crx)
